### ISSUE TITLE
Supported versions

### ISSUE THREAD

**Issue by christopher-b** [lando/ruby#38]
Hi folks, I'm wondering if we should remove older versions of ruby, and update the default version. 

This plugin still supports v1.9, which was [EOL'ed in 2015](https://www.ruby-lang.org/en/downloads/branches/). The default version, 2.7, was EOL'ed in early 2023. 

I'm not saying we should remove all versions that are out of support, but it's worth considering removing some of the very old versions, and updating the default version. Or at least marking more older versions as "legacy".

Thoughts?

**Comment by reynoldsalec** [comment]
Yeah moving to `legacy` seems good.

Only hitch with updating the default version is that anyone using the default will see their app get updated when they do a rebuild, which could be surprising. We're actually eliminating the concept of "default" versions in Lando v4 for this reason.

For this service I'd be inclined to say it's ok, since Ruby isn't _super_ well used and I'm guessing most people are specifying a version anyway (particularly because the default is probably pretty dated).

LMK if you need help getting a PR up @christopher-b!
